// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID           uuid.UUID
	WalletID     uuid.UUID
	Type         string
	Amount       int64
	BalanceAfter int64
	ReferenceID  uuid.NullUUID
	Note         sql.NullString
	CreatedAt    time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	FullName  string
	CreatedAt time.Time
}

type Wallet struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Balance   int64
	Currency  string
	CreatedAt time.Time
}
