// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID           pgtype.UUID        `json:"id"`
	WalletID     pgtype.UUID        `json:"wallet_id"`
	Type         string             `json:"type"`
	Amount       int64              `json:"amount"`
	BalanceAfter int64              `json:"balance_after"`
	ReferenceID  pgtype.UUID        `json:"reference_id"`
	Note         pgtype.Text        `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	FullName  string             `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
