// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (wallet_id, type, amount, balance_after, reference_id, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, wallet_id, type, amount, balance_after, reference_id, note, created_at
`

type CreateTransactionParams struct {
	WalletID     pgtype.UUID `json:"wallet_id"`
	Type         string      `json:"type"`
	Amount       int64       `json:"amount"`
	BalanceAfter int64       `json:"balance_after"`
	ReferenceID  pgtype.UUID `json:"reference_id"`
	Note         pgtype.Text `json:"note"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.ReferenceID,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByWalletID = `-- name: ListTransactionsByWalletID :many
SELECT id, wallet_id, type, amount, balance_after, reference_id, note, created_at
FROM transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByWalletIDParams struct {
	WalletID pgtype.UUID `json:"wallet_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByWalletID(ctx context.Context, arg ListTransactionsByWalletIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByWalletID, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
