// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, currency)
VALUES ($1, $2)
RETURNING id, user_id, balance, currency, created_at
`

type CreateWalletParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Currency string      `json:"currency"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, balance, currency, created_at
FROM wallets
WHERE user_id = $1 AND currency = $2
`

type GetWalletByUserIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Currency string      `json:"currency"`
}

func (q *Queries) GetWalletByUserID(ctx context.Context, arg GetWalletByUserIDParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserID, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets
SET balance = $1
WHERE id = $2
RETURNING id, user_id, balance, currency, created_at
`

type UpdateWalletBalanceParams struct {
	Balance int64       `json:"balance"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.Balance, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
